import {useEffect,useMemo,useRef,useState} from 'react';
import {Download,Info,Lock,RefreshCw} from 'lucide-react';
import {BleApiService,BleDatasetDetail} from '../../../app/services/bleApi';
import {failOperation,finishOperation,startOperation,updateOperation} from '../../../app/operations/operationTelemetry';

const api=new BleApiService();
type Def={label?:string;name?:string;human?:string;definition?:string;demonstrates?:string;does_not_demonstrate?:string;next?:string};
const humanTask:Record<string,string>={ble_activity:'Detección de actividad BLE',crc_valid_packets:'Paquetes BLE CRC-valid',windows_b200_corroboration:'Corroboración Windows–B200',logical_device_identification:'Identificación lógica del dispositivo',rf_fingerprint_preparation:'Preparación experimental para fingerprint RF'};

function Explain({label,definition,value}: {label:string;definition?:Def;value?:string}){
 const [open,setOpen]=useState(false),ref=useRef<HTMLSpanElement>(null);
 useEffect(()=>{const close=(event:KeyboardEvent)=>event.key==='Escape'&&setOpen(false);document.addEventListener('keydown',close);return()=>document.removeEventListener('keydown',close)},[]);
 const toggle=(event:React.KeyboardEvent|React.MouseEvent)=>{if('key'in event&&event.key!=='Enter'&&event.key!==' ')return;event.preventDefault();setOpen(x=>!x)};
 return <span ref={ref} className="relative inline-flex" onMouseEnter={()=>setOpen(true)} onMouseLeave={()=>setOpen(false)} onFocus={()=>setOpen(true)} onBlur={event=>{if(!ref.current?.contains(event.relatedTarget as Node))setOpen(false)}}><button type="button" aria-expanded={open} aria-haspopup="dialog" onClick={toggle} onKeyDown={toggle} className="inline-flex items-center gap-1 rounded underline decoration-dotted underline-offset-4 focus:outline-none focus:ring-2 focus:ring-sky-400">{label}<Info className="h-3 w-3 opacity-60"/></button>{open&&<span role="dialog" aria-label={`Explicación: ${label}`} tabIndex={0} className="absolute left-0 top-full z-50 mt-2 w-80 rounded-lg border border-sky-400/40 bg-slate-950 p-4 text-left text-xs leading-5 text-slate-200 shadow-2xl" onMouseEnter={()=>setOpen(true)} onMouseLeave={()=>setOpen(false)}><b className="block text-sm text-sky-300">{definition?.label||definition?.name||definition?.human||label}</b>{value&&<span className="mt-1 block text-emerald-300">Aplicado aquí: {value}</span>}<span className="mt-2 block">{definition?.definition||'Definición científica versionada no disponible.'}</span>{definition?.demonstrates&&<span className="mt-2 block"><b>Demuestra:</b> {definition.demonstrates}</span>}{definition?.does_not_demonstrate&&<span className="mt-1 block"><b>No demuestra:</b> {definition.does_not_demonstrate}</span>}{definition?.next&&<span className="mt-1 block"><b>Nivel siguiente:</b> {definition.next}</span>}</span>}</span>;
}
function Card({label,value,definition}:{label:string;value:unknown;definition?:Def}){return <div className="rounded-lg border border-slate-700 p-3"><div className="text-xs text-slate-400"><Explain label={label} definition={definition} value={String(value??'—')}/></div><div className="mt-1 text-xl font-semibold">{String(value??'—')}</div></div>}

export default function BleDatasetStudio(){
 const [detail,setDetail]=useState<BleDatasetDetail|null>(null),[defs,setDefs]=useState<Record<string,unknown>>({}),[sessions,setSessions]=useState<{session_id:string;state:string;target_address?:string}[]>([]),[selectedSession,setSelectedSession]=useState(''),[split,setSplit]=useState('session'),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[localProgress,setLocalProgress]=useState<{phase:string;percent?:number}|null>(null);
 const load=async()=>{setBusy(true);try{const [data,definitions,history]=await Promise.all([api.dataset('BLE-EVIDENCE-DS01'),api.datasetDefinitions(),api.hybridSessions()]);setDetail(data);setDefs(definitions);setSessions(history.filter(x=>x.state==='completed'));if(!selectedSession&&history.length)setSelectedSession(history.find(x=>x.state==='completed')?.session_id||'')}catch(error){const technical=error instanceof Error?error.message:'';setMessage(technical.includes('404')?'El backend activo es anterior a Dataset Studio. Reinicie con start_unified.ps1 para cargar las rutas nuevas.':technical||'Dataset Studio no disponible. Reinicie el backend.')}finally{setBusy(false)}};
 useEffect(()=>{void load()},[]);
 const glossary=((defs.ble_scientific_glossary as {terms?:Record<string,Def>})?.terms)||{},levels=((defs.evidence_level_definitions as {levels?:Record<string,Def>})?.levels)||{},qualityDefs=((defs.dataset_quality_definitions as {states?:Record<string,Def>})?.states)||{};
 const manifest=detail?.manifest,protocol=detail?.protocol||{},metrics=detail?.quality?.metrics||{},warnings=detail?.quality?.warnings||[],scientificStatus=detail?.quality?.scientific_status||{};
 const progress=manifest?`${manifest.sessions_completed} de ${manifest.campaigns_planned}`:'—';
 const ingest=async()=>{if(!selectedSession||!manifest)return;const operationId=`dataset-ingest:${selectedSession}`;setBusy(true);setMessage('');setLocalProgress({phase:'Leyendo ráfagas, paquetes y calidad',percent:10});startOperation({operationId,kind:'processing',title:'Generando ejemplos del dataset',phase:'Leyendo evidencias de la sesión',progressPercent:10,target:selectedSession,estimatedTotalSeconds:15,detail:`Dataset ${manifest.dataset_id} · no inicia una captura nueva`});try{updateOperation(operationId,{phase:'Aplicando niveles E0–E4 y cuarentena',progressPercent:45});setLocalProgress({phase:'Aplicando evidencia y exclusiones',percent:45});const next=await api.ingestDataset(manifest.dataset_id,manifest.version,{hybrid_session_id:selectedSession,day:1,planned_session:1});updateOperation(operationId,{phase:'Generando datasheet, métricas y SHA-256',progressPercent:90,processedItems:next.examples.length,totalItems:next.examples.length});setLocalProgress({phase:'Generando documentación e integridad',percent:90});setDetail(next);setMessage(`Sesión transformada: ${next.examples.length} ejemplos auditables.`);finishOperation(operationId,`${next.examples.length} ejemplos procesados`);setLocalProgress({phase:'Completado',percent:100})}catch(error){const text=error instanceof Error?error.message:'No se pudo ingerir.';setMessage(text);failOperation(operationId,text);setLocalProgress({phase:'Error'})}finally{setBusy(false);window.setTimeout(()=>setLocalProgress(null),2500)}};
 const freeze=async()=>{if(!manifest)return;setDetail(await api.freezeDataset(manifest.dataset_id,manifest.version));setMessage('Protocolo congelado; cualquier cambio requerirá una versión nueva.')};
 const createSplit=async()=>{if(!manifest)return;await api.splitDataset(manifest.dataset_id,manifest.version,split);await load();setMessage('Split generado por grupos independientes; comprobación de fuga superada.')};
 const examplesByState=useMemo(()=>Object.entries((metrics.exclusion_reasons as Record<string,number>)||{}),[metrics]);
 if(!detail)return <div className="rounded-xl border border-slate-700 p-6"><b>Dataset Studio</b><p className="mt-2 text-sm text-slate-400">{message||'Cargando metodología y evidencias…'}</p></div>;
 return <div className="space-y-4">
  <section className="rounded-xl border border-violet-500/40 bg-slate-900 p-5"><div className="text-xs font-bold uppercase tracking-[.2em] text-violet-300">Dataset Studio</div><h2 className="text-xl font-semibold">Generador de datasets RF verificables</h2><div className="mt-2 text-sm text-slate-300"><Explain label="IQ" definition={glossary.iq}/> + <Explain label="procedencia" definition={glossary.provenance}/> + calidad + confianza + <Explain label="evidencia verificable" definition={glossary.verifiable_evidence}/></div></section>
  <section className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Card label="Dataset" value={`${manifest?.dataset_id} · v${manifest?.version}`} definition={glossary.provenance}/><Card label="Progreso" value={progress} definition={glossary.session}/><Card label="Nivel máximo" value={manifest?.maximum_evidence_level} definition={levels[manifest?.maximum_evidence_level||'E0']}/><Card label="Fingerprinting" value="No validado" definition={levels.E5}/><Card label="Incluidos" value={manifest?.examples_included}/><Card label="Excluidos / cuarentena" value={manifest?.examples_excluded}/><Card label="Entrenamiento" value={manifest?.training_readiness}/><Card label="Duración por captura" value={`${String(protocol.duration_seconds??30)} s`} definition={{definition:'Duración RF congelada por condición. Generar ejemplos procesa una sesión existente y no vuelve a capturar el IoT.'}}/></section>
  <section className="rounded-xl border border-slate-700 p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><h3 className="font-semibold"><Explain label="Protocolo de campaña" definition={glossary.frozen_protocol}/></h3><p className="text-sm text-slate-400">Propósito: {humanTask[String(protocol.intended_task)]||String(protocol.intended_task)} · Canales {String(protocol.channels)} · {String(protocol.sample_rate_sps)} S/s · {String(protocol.bandwidth_hz)} Hz · {String(protocol.gain_db)} dB</p><p className="mt-1 text-xs text-slate-500"><Explain label="Pregunta científica" definition={{definition:String(protocol.research_question)}}/> · Mínimo {String(protocol.minimum_evidence_level)}</p></div>{!protocol.frozen?<button disabled={busy} onClick={()=>void freeze()} className="inline-flex items-center gap-2 rounded bg-violet-700 px-3 py-2 text-sm"><Lock className="h-4 w-4"/>Congelar protocolo</button>:<span className="rounded bg-emerald-500/15 px-3 py-2 text-sm text-emerald-300">Protocolo congelado</span>}</div></section>
  <section className="rounded-xl border border-slate-700 p-5"><h3 className="font-semibold">Incorporar una campaña híbrida existente</h3><p className="mt-1 text-xs text-slate-400">Generar ejemplos procesa una sesión terminada. Para leer datos nuevos del IoT, realiza antes una captura híbrida de {String(protocol.duration_seconds??30)} s con el dispositivo como objetivo.</p><div className="mt-3 flex flex-wrap gap-2"><select value={selectedSession} onChange={e=>setSelectedSession(e.target.value)} className="min-w-80 rounded bg-slate-800 p-2 text-sm">{sessions.map(s=><option key={s.session_id} value={s.session_id}>{s.session_id} · {s.target_address||'general'}</option>)}</select><button disabled={busy||!protocol.frozen} onClick={()=>void ingest()} className="rounded bg-sky-700 px-3 py-2 text-sm disabled:opacity-40">Generar ejemplos</button><button onClick={()=>void load()} className="rounded border border-slate-600 p-2" aria-label="Actualizar"><RefreshCw className="h-4 w-4"/></button></div>{localProgress&&<div className="mt-3 rounded border border-sky-500/30 bg-sky-500/10 p-3"><div className="flex justify-between text-sm"><span>{localProgress.phase}</span><b>{localProgress.percent==null?'—':`${localProgress.percent}%`}</b></div><div className="mt-2 h-2 overflow-hidden rounded bg-slate-800"><div className="h-full bg-sky-500 transition-all" style={{width:`${localProgress.percent??15}%`}}/></div></div>}{message&&<p className="mt-2 text-sm text-sky-300">{message}</p>}</section>
  <section className="rounded-xl border border-slate-700 p-5"><h3 className="font-semibold">Matriz experimental</h3><div className="mt-3 max-h-72 overflow-auto"><table className="w-full text-left text-xs"><thead><tr>{['Modelo','Unidad física','Día','Sesión','Canal','Distancia','Orientación','Ganancia','Estado','Nivel','Calidad'].map(x=><th key={x} className="p-2">{x==='Unidad física'?<Explain label={x} definition={glossary.physical_unit}/>:x}</th>)}</tr></thead><tbody>{detail.matrix.map((r,i)=><tr key={i} className="border-t border-slate-800">{['device_model','physical_unit_id','day','planned_session','channel','distance','orientation','gain_db','state','evidence_level','quality'].map(k=><td key={k} className="p-2">{String(r[k]??'—')}</td>)}</tr>)}</tbody></table></div></section>
  <div className="grid gap-4 lg:grid-cols-2"><section className="rounded-xl border border-slate-700 p-5"><h3 className="font-semibold">Composición y calidad</h3><div className="mt-3 grid grid-cols-2 gap-2"><Card label="CRC yield" value={`${String(metrics.crc_yield_percent??0)} %`} definition={{definition:`${detail.examples.filter(x=>x.crc_valid).length} paquetes CRC válidos / ${detail.examples.length} ejemplos. No mide identidad física.`}}/><Card label="Correlation yield" value={`${String(metrics.correlation_yield_percent??0)} %`}/><Card label="Overflows" value={metrics.overflows} definition={{definition:`Se registraron ${String(metrics.overflows??0)} posibles pérdidas. Impactan en preparación para fingerprinting.`}}/><Card label="Discontinuidades" value={metrics.discontinuities}/></div>{warnings.length>0&&<div className="mt-3 rounded bg-amber-500/10 p-3 text-sm text-amber-300">Advertencias: {warnings.join(' · ')}</div>}</section><section className="rounded-xl border border-slate-700 p-5"><h3 className="font-semibold">Inclusión y cuarentena</h3><div className="mt-3 space-y-2">{examplesByState.map(([state,count])=><div key={state} className="flex justify-between rounded border border-slate-800 p-2 text-sm"><Explain label={qualityDefs[state]?.human||state} definition={qualityDefs[state]} value={`${count} ejemplos`}/><b>{count}</b></div>)}{!examplesByState.length&&<p className="text-sm text-slate-400">Aún no hay ejemplos.</p>}</div></section></div>
  <section className="rounded-xl border border-slate-700 p-5"><h3 className="font-semibold"><Explain label="Split sin fuga" definition={glossary.leakage}/></h3><div className="mt-3 flex flex-wrap gap-2"><select value={split} onChange={e=>setSplit(e.target.value)} className="rounded bg-slate-800 p-2 text-sm">{[['session','por sesión'],['day','por día'],['physical_unit','por unidad física'],['channel','por canal'],['location','por ubicación'],['receiver','por receptor']].map(([v,l])=><option value={v} key={v}>{l}</option>)}</select><button disabled={!detail.examples.length} onClick={()=>void createSplit()} className="rounded bg-emerald-700 px-3 py-2 text-sm disabled:opacity-40">Generar split</button><span className="p-2 text-sm text-slate-400">{String(detail.split.leakage_check||'pendiente')}</span></div></section>
  <section className="rounded-xl border border-slate-700 p-5"><h3 className="font-semibold">Exportación versionada</h3><div className="mt-3 flex flex-wrap gap-2">{[['complete','Dataset completo'],['e4','Sólo E4'],['crc_valid','CRC-valid'],['negatives','Negativos'],['clean','Capturas limpias'],['metadata_only','Metadatos sin IQ'],['split_manifest','Manifiesto de split']].map(([kind,label])=><a key={kind} href={api.datasetExportUrl(manifest!.dataset_id,manifest!.version,kind)} className="inline-flex items-center gap-1 rounded border border-slate-600 px-3 py-2 text-sm"><Download className="h-4 w-4"/>{label}</a>)}</div><p className="mt-2 text-xs text-slate-500">Cada exportación incluye manifest, Dataset Datasheet y checksums SHA-256. E5 nunca se asigna automáticamente.</p></section>
 </div>;
}
