import React, { useEffect, useMemo, useState } from 'react';
import { AlertTriangle, Bluetooth, Download, Play, RefreshCw, RotateCcw, Square } from 'lucide-react';
import { Link, useNavigate, useParams } from 'react-router-dom';
import { BleAdvertisement, BleAdvertiser, BleApiService, BleCapabilities, BleJob, BleJobEvent, BlePacket } from '../../../app/services/bleApi';

const api = new BleApiService();
const replayNotice = 'This result was produced from a validated bitstream replay. No IQ demodulation or RF recovery was performed.';
export const BLE_DSP_UNAVAILABLE_REASON = 'IQ-based BLE analysis is unavailable because the DSP recovery gate has not been completed. Validated bitstream replay is available for platform-integration testing.';
const Panel: React.FC<React.PropsWithChildren<{ title: string }>> = ({ title, children }) => <section className="rounded-xl border border-slate-700 bg-slate-900 p-4"><h2 className="mb-3 text-sm font-semibold uppercase tracking-wider text-cyan-200">{title}</h2>{children}</section>;
const Metric = ({ label, display }: { label: string; display: React.ReactNode }) => <div className="rounded-lg border border-slate-700 bg-slate-950 p-3"><div className="text-xs text-slate-400">{label}</div><div className="mt-1 font-semibold">{display}</div></div>;
const summaryNumber = (summary: Record<string, unknown> | undefined, ...keys: string[]) => Number(keys.map((key) => summary?.[key]).find((item) => item !== undefined) ?? 0);

export const BleCapabilityStatus = ({ capabilities }: { capabilities: BleCapabilities | null }) => {
  const rows = [['Bit-true primitives', 'bit_true_gate', 'passed'], ['Link Layer bitstream decoder', 'link_layer_bitstream_gate', 'passed'], ['Advertising semantic parser', 'semantic_advertising_gate', 'passed'], ['Platform integration', 'platform_integration_gate', 'in_progress'], ['IQ/DSP recovery', 'dsp_gate', 'not_started'], ['OTA validation', 'ota_validated', 'not_performed']];
  return <Panel title="Capability status"><dl className="grid gap-x-6 md:grid-cols-2">{rows.map(([label, key, fallback]) => <div key={key} className="flex justify-between border-b border-slate-800 py-2 text-sm"><dt>{label}</dt><dd className="font-semibold text-amber-300">{String(capabilities?.gates[key] ?? fallback).replaceAll('_', ' ')}</dd></div>)}<div className="flex justify-between border-b border-slate-800 py-2 text-sm"><dt>Normative conformance</dt><dd className="font-semibold text-amber-300">{(capabilities?.normative_conformance ?? 'not_established').replaceAll('_', ' ')}</dd></div></dl></Panel>;
};

export const BleJobLauncher = ({ enabled, onCreated }: { enabled: boolean; onCreated: (job: BleJob) => void }) => { const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const launch = async () => { setBusy(true); setError(''); try { onCreated(await api.createReplayJob()); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Unable to create replay job'); } finally { setBusy(false); } }; return <Panel title="Platform integration test"><p className="mb-3 text-sm text-slate-300">Run the frozen Gate 1B campaign. Input mode: <strong>Validated bitstream replay</strong>.</p><button onClick={() => void launch()} disabled={!enabled || busy} className="inline-flex items-center gap-2 rounded-lg bg-cyan-600 px-4 py-2 text-sm font-semibold disabled:opacity-50"><Play className="h-4 w-4" />{busy ? 'Creating job…' : 'Start replay job'}</button>{error && <p className="mt-2 text-sm text-rose-300">{error}</p>}</Panel>; };

export const BleJobSummary = ({ job }: { job: BleJob }) => { const s = job.result_summary; const metrics: [string, React.ReactNode][] = [['CRC-valid packets', summaryNumber(s, 'confirmed_packet_count', 'crc_valid_packets')], ['Parsed advertising PDUs', summaryNumber(s, 'parsed_packet_count', 'parsed_advertising_pdus')], ['Advertising Data structures', summaryNumber(s, 'ad_structure_count')], ['Observed advertiser addresses', summaryNumber(s, 'advertiser_count')], ['PDU types observed', summaryNumber(s, 'pdu_type_count')], ['Channels represented', summaryNumber(s, 'channel_count')], ['CRC-invalid diagnostic candidates', summaryNumber(s, 'crc_invalid_candidate_count')], ['Duplicate publications', summaryNumber(s, 'duplicate_publications')], ['Worker commit', String(job.worker?.worker_commit ?? job.worker?.commit ?? 'Unavailable')], ['Processing duration', job.processing_duration_seconds == null ? 'Unavailable' : `${job.processing_duration_seconds}s`], ['Input mode', 'Validated bitstream replay']]; return <Panel title="Job summary"><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{metrics.map(([label, display]) => <Metric key={label} label={label} display={display} />)}</div></Panel>; };

export const BleChannelMap = ({ represented }: { represented: number[] }) => <Panel title="Channel overview"><div className="grid grid-cols-5 gap-2 sm:grid-cols-8 lg:grid-cols-10">{Array.from({ length: 40 }, (_, channel) => { const present = represented.includes(channel); return <div key={channel} title={present ? 'represented_in_test_vector' : 'not_represented_in_test_vector'} className={`rounded border p-2 text-center text-xs ${present ? 'border-cyan-400 bg-cyan-400/15' : 'border-slate-700 text-slate-500'} ${channel >= 37 ? 'ring-1 ring-amber-400' : ''}`}><b>{channel}</b><div>{present ? 'represented' : 'not represented'}</div></div>; })}</div></Panel>;
export const BlePacketDetails = ({ packet }: { packet: BlePacket }) => <pre className="max-h-72 overflow-auto rounded bg-slate-950 p-3 text-xs">{JSON.stringify(packet, null, 2)}</pre>;
export const BlePacketTable = ({ packets }: { packets: BlePacket[] }) => { const [selected, setSelected] = useState<BlePacket | null>(null); return <Panel title="Confirmed packets"><div className="overflow-auto"><table className="w-full text-left text-sm"><thead className="text-slate-400"><tr><th className="p-2">Packet ID</th><th>PDU type</th><th>Channel</th><th>CRC</th></tr></thead><tbody>{packets.map((packet, index) => <tr key={packet.packet_id ?? index} onClick={() => setSelected(packet)} className="cursor-pointer border-t border-slate-800"><td className="p-2">{packet.packet_id ?? `packet-${index + 1}`}</td><td>{packet.pdu_type ?? 'Unknown'}</td><td>{packet.channel_index ?? 'Unknown'}</td><td className={packet.crc_valid ? 'text-emerald-300' : 'text-rose-300'}>{String(packet.crc_valid)}</td></tr>)}</tbody></table></div>{selected && <BlePacketDetails packet={selected} />}</Panel>; };
export const BleAdStructureViewer = ({ structures }: { structures: unknown[] }) => <pre className="max-h-64 overflow-auto rounded bg-slate-950 p-3 text-xs">{JSON.stringify(structures, null, 2)}</pre>;
export const BleAdvertisementDetails = ({ advertisement }: { advertisement: BleAdvertisement }) => <div><p className="mb-2 text-xs text-amber-200">An observed address is not a permanent device identity.</p><BleAdStructureViewer structures={advertisement.ad_structures ?? []} /></div>;
export const BleAdvertisementTable = ({ advertisements }: { advertisements: BleAdvertisement[] }) => { const [selected, setSelected] = useState<BleAdvertisement | null>(null); return <Panel title="Advertisements">{advertisements.map((ad, index) => <button key={ad.packet_id ?? index} onClick={() => setSelected(ad)} className="mb-2 flex w-full justify-between rounded border border-slate-700 p-2 text-sm"><span>{ad.pdu_type ?? 'Unknown PDU'}</span><span className="font-mono">{ad.advertiser_address ?? 'No address'}</span></button>)}{selected && <BleAdvertisementDetails advertisement={selected} />}</Panel>; };
export const BleAdvertiserTable = ({ advertisers }: { advertisers: BleAdvertiser[] }) => <Panel title="Observed advertiser addresses"><p className="mb-2 text-xs text-amber-200">Addresses are observations, not stable device identities.</p>{advertisers.map((advertiser, index) => <div key={`${advertiser.address}-${index}`} className="flex justify-between border-t border-slate-800 py-2 text-sm"><code>{advertiser.address ?? 'Unknown'}</code><span>{advertiser.address_type ?? 'unknown type'} · {advertiser.packet_count ?? 0}</span></div>)}</Panel>;
export const BleReceiverPipeline = ({ events }: { events: BleJobEvent[] }) => <Panel title="Receiver / job pipeline"><ol>{events.map((event, index) => <li key={event.sequence ?? index} className="mb-2 text-sm"><code className="mr-3 text-cyan-300">#{event.sequence ?? index + 1}</code>{event.previous_state ?? 'start'} → <b>{event.new_state ?? 'unknown'}</b> · {event.reason ?? 'no reason supplied'}</li>)}</ol></Panel>;
export const BleDiagnostics = ({ diagnostics }: { diagnostics: unknown }) => <Panel title="Diagnostics"><pre className="max-h-64 overflow-auto whitespace-pre-wrap text-xs">{JSON.stringify(diagnostics, null, 2)}</pre></Panel>;
export const BleKnownLimitations = () => <Panel title="Known limitations"><ul className="list-disc space-y-2 pl-5 text-sm text-slate-300"><li>{BLE_DSP_UNAVAILABLE_REASON}</li><li>RSSI, SNR, CFO, RF bursts, sample coverage and timing lock: Unavailable — DSP not implemented.</li><li>OTA validation: Not performed. Normative conformance: Not established.</li><li>Replay timestamps are sequence-derived, never RF timestamps.</li></ul></Panel>;
export const BleArtifactDownloads = ({ jobId, artifacts }: { jobId: string; artifacts: unknown }) => <Panel title="Artifacts"><a href={api.bundleUrl(jobId)} className="inline-flex items-center gap-2 rounded bg-slate-700 px-3 py-2 text-sm"><Download className="h-4 w-4" />Download reproducible bundle</a><pre className="mt-3 max-h-44 overflow-auto text-xs">{JSON.stringify(artifacts, null, 2)}</pre></Panel>;
export const BleWorkerProvenance = ({ capabilities, job }: { capabilities: BleCapabilities | null; job?: BleJob }) => <Panel title="Worker provenance"><div className="grid gap-2 text-sm md:grid-cols-2"><div>Frozen worker commit: <code>{capabilities?.worker_commit ?? 'Unavailable'}</code></div><div>Scientific status: <b>{capabilities?.scientific_status ?? 'BLE_P0_INCOMPLETE'}</b></div><div>Capability: <b>{capabilities?.capability_status ?? 'experimental'}</b></div><div>Job: <b>{job?.job_id ?? 'No job selected'}</b></div></div></Panel>;

export const BleLabView: React.FC = () => {
  const { jobId } = useParams(); const navigate = useNavigate(); const [capabilities, setCapabilities] = useState<BleCapabilities | null>(null); const [job, setJob] = useState<BleJob | null>(null); const [packets, setPackets] = useState<BlePacket[]>([]); const [advertisements, setAdvertisements] = useState<BleAdvertisement[]>([]); const [advertisers, setAdvertisers] = useState<BleAdvertiser[]>([]); const [events, setEvents] = useState<BleJobEvent[]>([]); const [channels, setChannels] = useState<unknown>([]); const [diagnostics, setDiagnostics] = useState<unknown>([]); const [artifacts, setArtifacts] = useState<unknown>([]); const [error, setError] = useState('');
  const load = async () => { setError(''); try { setCapabilities(await api.capabilities()); if (!jobId) return; setJob(await api.job(jobId)); const results = await Promise.allSettled([api.packets(jobId), api.advertisements(jobId), api.advertisers(jobId), api.resource<unknown>(jobId, 'channels'), api.resource<BleJobEvent[]>(jobId, 'events'), api.resource<unknown>(jobId, 'diagnostics'), api.resource<unknown>(jobId, 'artifacts')]); const item = <T,>(index: number, fallback: T) => results[index].status === 'fulfilled' ? (results[index] as PromiseFulfilledResult<T>).value : fallback; setPackets(item(0, [])); setAdvertisements(item(1, [])); setAdvertisers(item(2, [])); setChannels(item(3, [])); setEvents(item(4, [])); setDiagnostics(item(5, [])); setArtifacts(item(6, [])); } catch (reason) { setError(reason instanceof Error ? reason.message : 'BLE API unavailable'); } };
  useEffect(() => { void load(); }, [jobId]);
  const represented = useMemo(() => (Array.isArray(channels) ? channels : []).map((entry) => typeof entry === 'number' ? entry : Number((entry as Record<string, unknown>).channel_index ?? (entry as Record<string, unknown>).channel)).filter(Number.isFinite), [channels]);
  const active = job && ['created', 'queued', 'validating_input', 'starting_worker', 'running', 'validating_artifacts', 'cancel_requested'].includes(job.state);
  return <div className="min-h-full bg-slate-950 p-6 text-slate-100"><div className="mx-auto max-w-7xl space-y-5"><header className="rounded-xl border border-cyan-800 bg-gradient-to-r from-slate-900 to-cyan-950 p-5"><div className="flex justify-between gap-4"><div><div className="flex items-center gap-2 text-cyan-300"><Bluetooth className="h-6 w-6" /><span className="text-xs font-bold uppercase tracking-[.2em]">Experimental passive analyzer</span></div><h1 className="mt-2 text-2xl font-bold">Bluetooth LE Analysis</h1><p>LE 1M primary advertising</p></div><div className="flex gap-2"><Link to="/ble-lab" className="rounded bg-slate-700 px-3 py-2 text-sm">BLE Lab home</Link><button onClick={() => void load()} className="rounded bg-slate-700 p-2"><RefreshCw className="h-4 w-4" /></button></div></div></header><div className="rounded-xl border border-amber-600 bg-amber-950/50 p-4 text-sm font-semibold text-amber-100"><AlertTriangle className="mr-2 inline h-4 w-4" />{replayNotice}</div>{error && <div className="rounded border border-rose-600 bg-rose-950 p-3">{error}</div>}<BleCapabilityStatus capabilities={capabilities} />{!jobId && <BleJobLauncher enabled={Boolean(capabilities?.enabled)} onCreated={(created) => navigate(`/ble-lab/jobs/${created.job_id}`)} />}{job && <><div className="flex justify-between rounded-xl border border-slate-700 bg-slate-900 p-4"><div><code>{job.job_id}</code><div className="mt-1 text-lg font-semibold">{job.state.replaceAll('_', ' ')}</div></div><div>{active && <button onClick={async () => setJob(await api.cancel(job.job_id))} className="mr-2 inline-flex gap-2 rounded bg-rose-700 px-3 py-2 text-sm"><Square className="h-4 w-4" />Cancel</button>}{['failed', 'timed_out', 'cancelled'].includes(job.state) && <button onClick={async () => { const next = await api.retry(job.job_id); navigate(`/ble-lab/jobs/${next.job_id}`); }} className="inline-flex gap-2 rounded bg-amber-600 px-3 py-2 text-sm"><RotateCcw className="h-4 w-4" />Retry</button>}</div></div><BleJobSummary job={job} /><BleChannelMap represented={represented} /><div className="grid gap-5 xl:grid-cols-2"><BlePacketTable packets={packets} /><BleAdvertisementTable advertisements={advertisements} /><BleAdvertiserTable advertisers={advertisers} /><BleReceiverPipeline events={events} /><BleDiagnostics diagnostics={diagnostics} /><BleArtifactDownloads jobId={job.job_id} artifacts={artifacts} /></div></>}<BleWorkerProvenance capabilities={capabilities} job={job ?? undefined} /><BleKnownLimitations /></div></div>;
};
